# Generated by Django 5.2.1 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_like_unique_together_notification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("movie", "user")},
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("like", "좋아요"), ("comment", "댓글")],
                max_length=10,
            ),
        ),
    ]
