# Generated by Django 5.2.1 on 2025-05-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_uploaded_at_movie_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(upload_to=''),
        ),
    ]
