version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myflix
      POSTGRES_USER: myflixuser
      POSTGRES_PASSWORD: myflixpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn myflix.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "1"
      SECRET_KEY: "your-secret-key"
      DJANGO_ALLOWED_HOSTS: "*"
      DB_NAME: myflix
      DB_USER: myflixuser
      DB_PASSWORD: myflixpass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: