apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myflix-secret
  namespace: myflix
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: myflix-secret-store
  target:
    name: myflix-secret
    creationPolicy: Owner
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: prod/myflix
        property: django_secret_key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: prod/myflix
        property: db_password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: prod/myflix
        property: redis_password
