apiVersion: v1
kind: ServiceAccount
metadata:
  name: myflix-app
  namespace: myflix
  annotations:
    # Optional: IRSA role ARN for S3/Secrets access
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/myflix-app-irsa
