apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web
  namespace: myflix
spec:
  selector:
    matchLabels:
      app: web
  namespaceSelector:
    matchNames:
      - myflix
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
