apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: myflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: myflix-app
      containers:
        - name: web
          image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/myflix-prod-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: myflix-config
            - secretRef:
                name: myflix-secret
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: myflix
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 8000
      targetPort: 8000
