apiVersion: v1
kind: Secret
metadata:
  name: postgres-ha-secret
  namespace: myflix
type: Opaque
stringData:
  POSTGRESQL_POSTGRES_PASSWORD: "postgres_admin_password"
  POSTGRESQL_PASSWORD: "backend_user_password"
  REPMGR_PASSWORD: "repmgr_password"
  PGPOOL_ADMIN_PASSWORD: "pgpool_admin_password"
  EXPORTER_DATA_SOURCE_NAME: "postgresql://backend_user:backend_user_password@postgres.myflix.svc.cluster.local:5432/Django_DB?sslmode=disable"
