apiVersion: v1
kind: ConfigMap
metadata:
  name: myflix-config
  namespace: myflix
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "myflix.example.com"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://myflix.example.com"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "Django_DB"
  DB_USER: "backend_user"
  GUNICORN_WORKERS: "3"
  GUNICORN_TIMEOUT: "600"
  GUNICORN_GRACEFUL_TIMEOUT: "60"
  VIDEO_WORKER_POLL_INTERVAL: "3"
