# Generated by Django 5.2.1 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_status',
            field=models.CharField(
                choices=[('queued', '대기 중'), ('processing', '처리 중'), ('ready', '재생 가능'), ('failed', '처리 실패')],
                default='ready',
                max_length=20,
            ),
        ),
    ]
